DROP TABLE IF EXISTS apply_lecture;
DROP TABLE IF EXISTS lecture;
create table lecture (max_applicant_count integer, id bigint generated by default as identity, start_date_time timestamp(6), content varchar(255), name varchar(255), room varchar(255), speaker varchar(255), primary key (id));
create table apply_lecture (employee_id varchar(5) not null, apply_date_time timestamp(6), lecture_id bigint not null, primary key (employee_id, lecture_id));
alter table if exists apply_lecture add constraint fk_apply_lecture foreign key (lecture_id) references lecture;